services:
  nginx:
    image: nginx
    ports:
      - '81:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './static_files:/usr/share/nginx/html/static_files'
      - './mediafiles:/usr/share/nginx/html/mediafiles'