# Generated by Django 5.2.1 on 2025-05-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='strength', max_length=20)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg/lbs', max_digits=6, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Duration for cardio exercises', null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km/miles for cardio', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['workout', 'id'],
            },
        ),
    ]
