# Generated by Django 5.2.1 on 2025-05-19 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the workout session', max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when the workout occurred')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the workout (HH:MM:SS)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the workout', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
