# Generated by Django 5.2.1 on 2025-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.ManyToManyField(related_name='workouts', to='workouts.musclegroup'),
        ),
    ]
