# Generated by Django 5.2.1 on 2025-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
