# Generated by Django 5.2.1 on 2025-07-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='workout',
        ),
    ]
