# Generated by Django 5.2.1 on 2025-07-16 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_muscle_group_workout_muscle_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='musclegroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ManyToManyField(related_name='workouts', to='workouts.workouttype'),
        ),
    ]
